version: '3.1'

services:

  postgres:
    image: 'pedronobrega/dockerpostgres'
    container_name: 'postgres'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'typeorm'
      POSTGRES_USER: 'typeorm'
      POSTGRES_PASSWORD: 'typeorm'

  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'rabbit'
    restart: 'always'
    ports:
      - '15672:15672'
      - '5672:5672'

  node:
    image: 'pedronobrega/dockernode'
    container_name: 'node'
    restart: 'always'
    ports:
      - '3333:3333'
    links:
      - 'postgres'
      - 'rabbit'
