{application,amqp,
             [{applications,[kernel,stdlib,elixir,lager,amqp_client]},
              {description,"Idiomatic Elixir client for RabbitMQ.\n"},
              {modules,['Elixir.AMQP','Elixir.AMQP.Application',
                        'Elixir.AMQP.Basic','Elixir.AMQP.BasicError',
                        'Elixir.AMQP.Channel','Elixir.AMQP.Channel.Receiver',
                        'Elixir.AMQP.Channel.ReceiverManager',
                        'Elixir.AMQP.Confirm','Elixir.AMQP.Connection',
                        'Elixir.AMQP.Core','Elixir.AMQP.DirectConsumer',
                        'Elixir.AMQP.Exchange','Elixir.AMQP.Queue',
                        'Elixir.AMQP.Utils']},
              {registered,[]},
              {vsn,"1.6.0"},
              {mod,{'Elixir.AMQP.Application',[]}}]}.
